def imageName = 'mlabouardy/movies-loader'
 
node('workers'){
    stage('Checkout'){
        checkout scm
    }
 
    stage('Unit Tests'){
        sh "docker -v /var/run/docker.sock:/var/run/docker.sock build -t ${imageName}-test -f Dockerfile.test ."
        sh "docker -v /var/run/docker.sock:/var/run/docker.sock run --rm ${imageName}-test"
    }
}