def imageName = 'mlabouardy/movies-loader'
 
node('workers'){
    stage('Checkout'){
        checkout scm
    }
    dir('/chapter8/pipelines/movies-loader'){
        sh "pwd"
    } 
    stage('Unit Tests'){
        sh "docker build -t ${imageName}-test -f Dockerfile.test ."
        sh "docker run --rm ${imageName}-test"
    }
}